spring.profiles.active=local
#spring.profiles.active=prod

spring.application.name=petcare

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

# JSP 사용 시 (Thymeleaf 미사용)
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# 파일 업로드
file.upload-dir=C:/upload/
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#SQL은 XML(또는 어노테이션)에 써놓고 
#MyBatis는 SQL실행 결과를 자바객체(VO)로 바꿔주는 역할(SQL매핑 프레임워크) 
#mybatis.mapper-location : SQL이 적힌 XML파일들이 어디있는지 찾는것
#XML 매퍼 파일들을 resources/mybatis 폴더 밑에서 찾겠다는 뜻
mybatis.mapper-locations=classpath:mybatis/**/*.xml
#카멜케이스로 자동매핑(없으면 컬럼명 일일이 alias 필요)
mybatis.configuration.map-underscore-to-camel-case=true

# api-key (실제 키는 application-local.properties 에 작성)
public.service-api-key=${PUBLIC_SERVICE_API_KEY}
smarttracker.api-key=${SMARTTRACKER_API_KEY}

kakao.rest-api-key=${KAKAO_REST_API_KEY}
kakao.client-secret=${KAKAO_CLIENT_SECRET}
kakao.js-api-key=${KAKAO_JS_API_KEY}

toss.client-key=${TOSS_CLIENT_KEY}
toss.secret-key=${TOSS_SECRET_KEY}
toss.billing.client-key=${TOSS_BILLING_CLIENT_KEY}
toss.billing.secret-key=${TOSS_BILLING_SECRET_KEY}

kftc.openbanking.client-id=${KFTC_OPENBANKING_CLIENT_ID}
kftc.openbanking.client-secret=${KFTC_OPENBANKING_CLIENT_SECRET}
kftc.openbanking.mock=true

#uri
kakao.redirect-uri=http://localhost:8080/oauth/kakao/callback
kftc.openbanking.base-url=https://testapi.openbanking.or.kr

#smtp
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.com.petcare.petcare.biz.mapper=DEBUG

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG