BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BUSINESS CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;


CREATE TABLE BUSINESS (
    ID              NUMBER              GENERATED BY DEFAULT ON NULL AS IDENTITY    PRIMARY KEY, 
    MEMBER_ID       VARCHAR2(50)        NOT NULL,
    TYPE            VARCHAR2(10)        NOT NULL,
    BIZNO           VARCHAR2(12)        NOT NULL,
    NAME            VARCHAR2(100)       NOT NULL,
    CEO             VARCHAR2(50)        NOT NULL,
    PHONE           VARCHAR2(20)        NOT NULL,
    ZIPCODE         VARCHAR2(10)        NOT NULL,
    ADDR1           VARCHAR2(200)       NOT NULL,
    ADDR2           VARCHAR2(200)       NOT NULL,
    STATUS          VARCHAR2(10)        NOT NULL,
    APPROVED        DATE                NULL,
    CREATED         DATE                NOT NULL 
);

CREATE TABLE HOSPITAL (
    ID              NUMBER              GENERATED BY DEFAULT ON NULL AS IDENTITY    PRIMARY KEY, 
    BIZ_ID          NUMBER	            NOT NULL,
    NAME            VARCHAR2(100)       NOT NULL,
    PHONE           VARCHAR2(20)        NOT NULL,
    ZIPCODE         VARCHAR2(10)        NOT NULL,
    ADDR1           VARCHAR2(300)       NOT NULL,
    ADDR2           VARCHAR2(200)       NOT NULL,
    LAT             NUMBER(10,7)        NULL,  
    LNG             NUMBER(10,7)        NULL,  
    DESCRIPTION     VARCHAR2(2000)      NULL,  
    TAGS            VARCHAR2(500)       NULL,  
    
    TIMETABLE       CLOB                NULL,  
    
    STATUS          VARCHAR2(10)        NOT NULL,
    CREATED         DATE                NOT NULL 
);

CREATE TABLE STAY (
    ID              NUMBER              GENERATED BY DEFAULT ON NULL AS IDENTITY    PRIMARY KEY, 
    BIZ_ID		    NUMBER              NULL,  
    NAME            VARCHAR2(200)       NULL,  
    PHONE		    VARCHAR2(20) 	    NULL,  
    ZIPCODE         VARCHAR2(10)        NULL,  
    ADDR1           VARCHAR2(200)       NULL,  
    ADDR2		    VARCHAR2(200) 	    NULL,  
    LAT             VARCHAR2(200)       NULL,  
    LNG             VARCHAR2(200)       NULL,  
    DESCRIPTION     CLOB                NULL,  
    TAGS            VARCHAR2(500)       NULL,
    CHECKIN         VARCHAR2(20)        NULL,  
    CHECKOUT        VARCHAR2(20)        NULL,  
    PET_FEE         VARCHAR2(200)       NULL,      
    PET_POLICY      CLOB                NULL,  
    REFUND_POLICY   CLOB                NULL,  
    REGION		    VARCHAR2(20) 	    NULL
    STATUS          VARCHAR2(200)       NULL,  
    CREATED         DATE                NOT NULL 
);

CREATE TABLE ROOM (
    ID              NUMBER              GENERATED BY DEFAULT ON NULL AS IDENTITY    PRIMARY KEY,
    STAY_ID         NUMBER              NOT NULL,  
    NAME            VARCHAR2(100)       NOT NULL,  
    PRICE           NUMBER              NOT NULL,  
    MAXPEOPLE       NUMBER              NULL,  
    MAXPET          NUMBER              NULL,  
    STATUS          VARCHAR2(10)        NOT NULL,  -- (PENDING/APPROVE/REJECT)
    CREATED         DATE                NOT NULL 
);

CREATE TABLE FILES (
    ID              NUMBER              GENERATED BY DEFAULT ON NULL AS IDENTITY    PRIMARY KEY, 
    REF_TYPE        VARCHAR2(20)        NOT NULL,
    REF_ID          NUMBER              NOT NULL, 
    URL             VARCHAR2(500)       NOT NULL,
    FILENAME        VARCHAR2(200)       NULL,
    CREATED         DATE                NOT NULL
);

CREATE TABLE MEMBER (
    ID              VARCHAR2(50)        PRIMARY KEY,  
    PASSWORD        VARCHAR2(200)       NOT NULL,  
    NAME            VARCHAR2(50)        NOT NULL,  
    EMAIL           VARCHAR2(100)       NOT NULL,  
    PHONE           VARCHAR2(20)        NOT NULL,  
    ZIPCODE         VARCHAR2(10)        NULL,  
    ADDR1           VARCHAR2(200)       NULL,  
    ADDR2           VARCHAR2(100)       NULL,  
    POINT           NUMBER(10)          NULL,  
    ROLE            VARCHAR2(20)        NOT NULL,
    AGREESERVICE    VARCHAR2(20)        NOT NULL,
    AGREEPRIVACY    VARCHAR2(20)        NOT NULL,
    AGREELOCATION   VARCHAR2(20)        NOT NULL,
    AGREEMARKETING  VARCHAR2(20)        NOT NULL,
    CREATED         DATE                NOT NULL 
);

CREATE TABLE MEMBER_SOCIAL (
    MEMBER_ID       NUMBER              PRIMARY KEY,
    PROVIDER        VARCHAR2(20)        NOT NULL,
    PROVIDER_UID    VARCHAR2(200)       NOT NULL,
    CREATED         DATE                NOT NULL 
);

CREATE TABLE PET (
    ID              NUMBER              GENERATED BY DEFAULT ON NULL AS IDENTITY    PRIMARY KEY,
    MEMBER_ID       NUMBER              NOT NULL, 
    NAME            VARCHAR2(30)        NOT NULL, 
    TYPE            VARCHAR2(10)        NOT NULL, 
    SPECIES         VARCHAR2(50)        NULL,  
    GENDER          CHAR(1)             NULL,  
    AGE             NUMBER(3)           NULL,  
    WEIGHT          NUMBER(5,1)         NULL,  
    CREATED         DATE                NOT NULL  
);

CREATE TABLE RESERVATION (
    ID              VARCHAR2(20)        GENERATED BY DEFAULT ON NULL AS IDENTITY    PRIMARY KEY,
    TYPE            VARCHAR2(20)        NOT NULL,
    BIZ_ID          NUMBER              NOT NULL,
    MEMBER_ID       VARCHAR2(50)        NOT NULL,
    PET_ID          NUMBER,
    MEMO            VARCHAR2(500),
    STATUS          VARCHAR2(20)        DEFAULT 'PENDING',
    REJECT          VARCHAR2(500),
    CREATED         DATE                DEFAULT SYSDATE,

    RESV_DATE       DATE,
    RESV_TIME       VARCHAR2(10),

    CHECKIN_DATE    DATE,
    CHECKOUT_DATE   DATE,

    SYMPTOMS        VARCHAR2(500)
);


CREATE TABLE PRODUCT (
    ID              NUMBER              GENERATED BY DEFAULT ON NULL AS IDENTITY    PRIMARY KEY,
    CODE            VARCHAR2(100)       NOT NULL,
    NAME            VARCHAR2(200)       NOT NULL,
    BRAND           VARCHAR2(200)       NOT NULL,
    CATEGORY_ID     NUMBER              NOT NULL,
    PRICE           NUMBER              NOT NULL,
    SALE            NUMBER              NULL
);

CREATE TABLE PRODUCT_CATEGORY (
    ID              NUMBER              GENERATED BY DEFAULT ON NULL AS IDENTITY    PRIMARY KEY,
    PARENT_ID       NUMBER              NULL, 
    NAME            VARCHAR2(200)       NULL, 
    DEPTH           VARCHAR2(200)       NULL, 
    STATUS          NUMBER(1)           DEFAULT 0
);